// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvvhEAvQPZ4KCSNXb-0XoTSNfbGU00-Fc',
    appId: '1:605486384693:web:592708574fce57a4db937c',
    messagingSenderId: '605486384693',
    projectId: 'sprint3-62089',
    authDomain: 'sprint3-62089.firebaseapp.com',
    storageBucket: 'sprint3-62089.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLw_NN0qA7noulTX7qYFFJV1NTYQEaExE',
    appId: '1:605486384693:android:3d04a5c380f786f3db937c',
    messagingSenderId: '605486384693',
    projectId: 'sprint3-62089',
    storageBucket: 'sprint3-62089.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrTttrkb412Az4LPuIXgurSCTJE7P3DgQ',
    appId: '1:605486384693:ios:941557e2ce0f5c60db937c',
    messagingSenderId: '605486384693',
    projectId: 'sprint3-62089',
    storageBucket: 'sprint3-62089.firebasestorage.app',
    iosBundleId: 'com.example.sprint3App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrTttrkb412Az4LPuIXgurSCTJE7P3DgQ',
    appId: '1:605486384693:ios:941557e2ce0f5c60db937c',
    messagingSenderId: '605486384693',
    projectId: 'sprint3-62089',
    storageBucket: 'sprint3-62089.firebasestorage.app',
    iosBundleId: 'com.example.sprint3App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvvhEAvQPZ4KCSNXb-0XoTSNfbGU00-Fc',
    appId: '1:605486384693:web:75be6dd9e83f7bd2db937c',
    messagingSenderId: '605486384693',
    projectId: 'sprint3-62089',
    authDomain: 'sprint3-62089.firebaseapp.com',
    storageBucket: 'sprint3-62089.firebasestorage.app',
  );
}
